version: '3'

services:
  client:
    build: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  server:
    build: ./server
    command: bash -c "python3 server/manage.py runserver 0.0.0.0:8000"
    container_name: server
    volumes:
      - .:/server
    ports:
      - '8000:8000'